### ISSUE TITLE
Subtask form incomplete

### ISSUE THREAD

**Issue by theedo** [phpcollab/phpcollab#74]
Debian 11 Bullseye
- [] phpCollab version: 2.10.3
- [] PHP version: 7.4.25
- [] Web server: Apache2 version 2.4.51-1

- [] Steps to duplicate the problem
Add a task. Try and add subtask to task. Form appears incomplete and there is no submit button. Also the assign to dropdown does not get populated.

- [] Stacktraces and phpCollab/PHP DEBUG logs where appropriate.
Not applicable.

**Comment by mindblender** [comment]
@theedo Usually when a page does not render properly, in this case an incomplete form, there is usually an error in the generated HTML code.  Since you mention the "assign to" drop down is not getting populated, then I bet that if you inspect that element, or view page source, there will be an error buried in the code.  If you could provide that error, it will help me reproduce it.

**Comment by mindblender** [comment]
Fixed.  Will be in next release.
